### ISSUE TITLE
connects

### ISSUE THREAD

**Issue by lastdarken** [omghixd/Registration-Page-Mod#1]
resolved

**Comment by omghixd** [comment]
inc > settings.php

And fill out the information accordingly.

**Comment by lastdarken** [comment]
I usage this site https://github.com/FusionGen/FusionGen but my database hack

I want use just a Page register.

**Comment by omghixd** [comment]
This repository has nothing to do with FusionGen, But since i also actively contribute there i'd like for you to reply to the Issue Report you made over there. https://github.com/FusionGen/FusionGen/issues/10#issuecomment-626300527

- On-Topic: Did you manage to connect everything?

**Comment by alexandre433** [comment]
Sounds like a yes, main text was changed to "resolved"
